# -*- coding: utf-8 -*-
"""dicecup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I4Hbh4mgohnN6EEtpG8ZLPMVJBbl0np7
"""

import sys
import re
# We need this library to exit the program at end
#instantiate two variables to accept two values 


die1 = input("Please enter the value of the first roll: ")
die2 = input("Please enter the value of the second roll: ")

if bool(re.match('[a-zA-Z]+', die1)) or bool(re.match('[a-zA-Z]+', die2)) == True:
  sys.exit()
else:
  int(die1)
  int(die2)
      
if (
    die1 < 4 or die1 > 20 or # Fulfill constraints from problem
    die2 < 4 or die2 > 20
    ): 
    smaller_number = min(die1,die2)+1 #We'll take the smallest value of the inputs and assign it to a variable
    bigger_number = max(die1, die2)+1 #We'll take the larger value of the inputs and assign it to another variable
    tuple1 = tuple(range(smaller_number, bigger_number+1))
          #print(*tuple(range(smaller_number, bigger_number+1)), sep = "\n") #We'll use the list function to create a list of numbers between the smaller and larger number inputted by the user
    for elem in tuple1: #We iterate through all the values in our list by adding one and printing to screen
      print(elem+1)  
else:
  sys.exit()

